Traceback (most recent call last):
  File "/Users/jidali/bu/cs655/pa/pa1/pa1part2/server.py", line 114, in <module>
    main()
  File "/Users/jidali/bu/cs655/pa/pa1/pa1part2/server.py", line 73, in main
    server.socket.bind(server_address)
OSError: [Errno 48] Address already in use
Server is listening on ('', 58901)
Server is listening on ('', 58902)
Server is listening on ('', 58903)
Server is listening on ('', 58904)
Server is listening on ('', 58905)
Server is listening on ('', 58906)
404 ERROR: Invalid Measurement Message
Server is listening on ('', 58501)
Server is listening on ('', 58502)
Server is listening on ('', 58503)
Server is listening on ('', 58504)
Server is listening on ('', 58505)
Server is listening on ('', 58506)
